#==============================================================================
# HPRMAT Makefile
# High-Performance R-Matrix Solver
#==============================================================================

# Include configuration (generated by setup.sh)
-include make.inc

# Default compilers (can be overridden in make.inc)
FC ?= gfortran
CC ?= gcc
NVCC ?= nvcc

# Default flags
FFLAGS ?= -O3 -fopenmp
CFLAGS ?= -O3
NVCCFLAGS ?= -O3

# Default libraries
LIBS ?= -llapack -lblas -fopenmp

# Source directory
SRCDIR = src

# Object files
OBJS = $(SRCDIR)/precision.o \
       $(SRCDIR)/constants.o \
       $(SRCDIR)/rmat_solvers.o \
       $(SRCDIR)/rmatrix_hp.o \
       $(SRCDIR)/special_functions.o

# GPU objects (optional)
ifeq ($(GPU_ENABLED),true)
  OBJS += $(SRCDIR)/gpu_solver_interface.o $(SRCDIR)/cusolver_interface.o
  FFLAGS += -DGPU_ENABLED
  LIBS += -L$(CUDA_PATH)/lib64 -lcudart -lcusolver -lcublas -lstdc++
endif

# Library name
LIBNAME = libhprmat.a

#==============================================================================
# Targets
#==============================================================================

.PHONY: all clean install examples

all: $(LIBNAME)

$(LIBNAME): $(OBJS)
	ar rcs $@ $^
	@echo ""
	@echo "=== HPRMAT library built successfully ==="
	@echo "Library: $(LIBNAME)"
	@echo ""

# Module output directory
MODDIR = $(SRCDIR)

# Fortran compilation rules
$(SRCDIR)/precision.o: $(SRCDIR)/precision.F90
	$(FC) $(FFLAGS) -J$(MODDIR) -c $< -o $@

$(SRCDIR)/constants.o: $(SRCDIR)/constants.F90 $(SRCDIR)/precision.o
	$(FC) $(FFLAGS) -J$(MODDIR) -I$(MODDIR) -c $< -o $@

$(SRCDIR)/rmat_solvers.o: $(SRCDIR)/rmat_solvers.F90 $(SRCDIR)/precision.o
	$(FC) $(FFLAGS) -J$(MODDIR) -I$(MODDIR) -c $< -o $@

$(SRCDIR)/rmatrix_hp.o: $(SRCDIR)/rmatrix_hp.F90
	$(FC) $(FFLAGS) -J$(MODDIR) -I$(MODDIR) -c $< -o $@

$(SRCDIR)/special_functions.o: $(SRCDIR)/special_functions.f
	$(FC) $(FFLAGS) -c $< -o $@

# GPU compilation rules (if enabled)
$(SRCDIR)/gpu_solver_interface.o: $(SRCDIR)/gpu_solver_interface.F90 $(SRCDIR)/precision.o
	$(FC) $(FFLAGS) -J$(MODDIR) -I$(MODDIR) -c $< -o $@

$(SRCDIR)/cusolver_interface.o: $(SRCDIR)/cusolver_interface.cu
	$(NVCC) $(NVCCFLAGS) -arch=$(GPU_ARCH) -c $< -o $@

# Examples
examples: $(LIBNAME)
	@echo "Building examples..."
	$(MAKE) -C examples

# Clean
clean:
	rm -f $(SRCDIR)/*.o $(SRCDIR)/*.mod *.mod $(LIBNAME)
	@echo "Cleaned."

# Install (optional)
INSTALL_PREFIX ?= /usr/local
install: $(LIBNAME)
	mkdir -p $(INSTALL_PREFIX)/lib
	mkdir -p $(INSTALL_PREFIX)/include
	cp $(LIBNAME) $(INSTALL_PREFIX)/lib/
	cp $(SRCDIR)/*.mod $(INSTALL_PREFIX)/include/
	@echo "Installed to $(INSTALL_PREFIX)"

#==============================================================================
# Help
#==============================================================================

help:
	@echo "HPRMAT - High-Performance R-Matrix Solver"
	@echo ""
	@echo "Usage:"
	@echo "  ./setup.sh          # Configure (detect GPU, OpenBLAS)"
	@echo "  make                # Build library"
	@echo "  make examples       # Build examples"
	@echo "  make clean          # Clean build files"
	@echo "  make install        # Install (default: /usr/local)"
	@echo ""
	@echo "Configuration:"
	@echo "  Edit make.inc to customize compilers and libraries"
	@echo ""
